### PR TITLE
Smg spread 

### PR DESCRIPTION
**Pull request by Themostrandom**
- [ x ] This PR has been tested locally
- Suggestion : https://discord.com/channels/447819017391046687/1008040841102766153/1306254713175674981

--> ~~`spread = 2`~~ --> `spread = 1.3`

### CODE REVIEW

**Comment by Themostrandom** [comment]
I can also add this https://discord.com/channels/447819017391046687/1008040841102766153/1276904968581939254

**Comment by farooqkz** [comment]
> I can also add this https://discord.com/channels/447819017391046687/1008040841102766153/1276904968581939254

In general, one change per PR. I also get tempted to do some small stuff through one PR but it's usually not a good idea.

**Comment by Themostrandom** [comment]
> > I can also add this https://discord.com/channels/447819017391046687/1008040841102766153/1276904968581939254
> 
> In general, one change per PR. I also get tempted to do some small stuff through one PR but it's usually not a good idea.
> 
> I feel like `1.5` is a better choice than `1.3` as the current one is `2`

okay

**Comment by Themostrandom** [comment]
> > I can also add this https://discord.com/channels/447819017391046687/1008040841102766153/1276904968581939254
> 
> In general, one change per PR. I also get tempted to do some small stuff through one PR but it's usually not a good idea.
> 
> I feel like `1.5` is a better choice than `1.3` as the current one is `2`

Its done `spread= 1.5` now

**Comment by farooqkz** [comment]
@LoneWolfHT Merge?

**Pull request merged**
