### PR TITLE
Remove snipers

### PR DESCRIPTION
**Pull request by LoneWolfHT**
## How to test
* Join game and look at class list
* Make sure everything is worded properly/makes sense
* Try to use sniper as Knight and Shooter class

### CODE REVIEW

**Comment by KodaTheGuy** [comment]
From what i have seen this PR is completely fine

**Comment by KodaTheGuy** [comment]
Both Knights and Sharpshooter can't use sniper, everything is fine

**Comment by LoneWolfHT** [comment]
Sharpshooters can't use sniper? Are you sure you loaded it?

**Comment by olliy1or** [comment]
@KodaTheGuy sharpshooters should be able to use it and there shouldnt be  a class for sniper after this PR

**Pull request merged**
