### PR TITLE
Make it possible to send PMs through /pm

### PR DESCRIPTION
**Pull request by a-blob**

### CODE REVIEW

**Comment by farooqkz** [comment]
I don't see a reason why we need this.

**Comment by a-blob** [comment]
Since it says "PM from" when you receive a /msg, many people receiving it the first time will try /PM to reply.

**Comment by farooqkz** [comment]
> Since it says "PM from" when you receive a /msg, many people receiving it the first time will try /PM to reply.

Yeah but still I don't see any reason. We could simply add a hint when they receive a PM `reply with /msg` or even a new random message.

**Comment by a-blob** [comment]
How about "msg from...."?

**Comment by farooqkz** [comment]
> How about "msg from...."? Adding `reply with /msg` every time seems a bit spammy.

A random message then?

**Comment by a-blob** [comment]
I was thinking that maybe there could be a list opened by `/tips` that lists things such as how to change classes, how to send team messages, how to send PMs, etc... Random messages are easy to ignore and they only appear sometimes.

**Comment by farooqkz** [comment]
> I was thinking that maybe there could be a list opened by `/tips` that lists things such as how to change classes, how to send team messages, how to send PMs, etc... Random messages are easy to ignore and they only appear sometimes.

We could show all random messages in an Inventory tab.

**Comment by src4026** [comment]
> things such as how to change classes, how to send team messages, how to send PMs, etc... 
Perhaps a beginner's guide/ that can be accessed upon first joining. I am thinking of something like this, since we're on the topic of tips:
- An inventory tab that includes basic things in section like:
    - How to Play:
    - Modes
    - Learning
    - Using commands
- As for the "Using commands" section, I was thinking of an alternative method of making it an extra inventory tab listing out commands that are available to the normal CTF player, since using /help is time taking and can be made easier.
- This could be showed upon joining and be connected to the rules also, I haven't fully thought the process out in my head though, so it is subject to discussion as well.
Is this important enough to make an Issue for?

**Comment by a-blob** [comment]
Showing all random messages might be a bit clogged and confusing. I like s20's idea better.

**Comment by a-blob** [comment]
I drafted this simple mod for the game that adds a "Tips" inventory tab https://github.com/a-blob/capturetheflag/tree/inventory_tips/mods/other/inventory_tips
Of course both the title and the content in the tab is highly subject to change. The current content is a few selected random messages simplified to be shorter.
I'll close this PR for now and maybe make another one when the tips is done. In the mean-time feel free to create PRs there.

**Pull request closed without merging**
