### PR TITLE
Add mushroom farming

### PR DESCRIPTION
**Pull request by farooqkz**
- [x] This PR has been tested locally

This PR is a draft because I think it needs more polish. Or it might not need. Reviews are very welcome!

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
What happens if you time the per-step lua time with `(endtime - starttime) / 1e6` using `minetest.get_us_time()` for the times? Placing a lot of mushrooms to test with?

**Comment by farooqkz** [comment]
> What do you get if you time the per-step lua time with `(endtime - starttime) / 1e6` using `minetest.get_us_time()` for the times; Placing a lot of mushrooms to test with?

Not sure what you mean. Are you suggesting using this method instead of the current method with `globalstep`? BTW, This PR spawns mushrooms anywhere dark enough. So you don't need mushrooms to farm mushrooms. I think this is better since selfish players could prevent others from farming mushroom. If unsure, we can do a poll.

**Comment by LoneWolfHT** [comment]
> Not sure what you mean. Are you suggesting using this method instead of the current method with `globalstep`?

What I posted is how you measure how much lag it's causing, by timing how long it takes to get from the start of the globalstep to the end of it

**Comment by farooqkz** [comment]
Closing as it won't be merged.

**Pull request closed without merging**
