### PR TITLE
Add award

### PR DESCRIPTION
**Pull request by Emojigit**
Close https://github.com/MT-CTF/capturetheflag/issues/17
WIP
* Basic award
 * removed default awards, all awards are generated by `ctf_award` mod
TODO:
 * A lot of png that unused, will remove when the whole award system finishes
 * more awards

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
Note https://github.com/MT-CTF/capturetheflag/issues/17#issuecomment-439063525

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please fix [LuaCheck](https://github.com/MT-CTF/capturetheflag/runs/1648781459) warnings.

**Comment by LoneWolfHT** [comment]
Note this is a draft and not really ready for review yet

**Comment by rubenwardy** [comment]
You should use a submodule for awards, pointing at the gitlab repo

**Comment by Emojigit** [comment]
> You should use a submodule for awards, pointing at the GitLab repo

But how to disable default awards?

**Comment by rubenwardy** [comment]
> But how to disable default awards?

If there's not a setting, I'll add one

**Comment by Emojigit** [comment]
Replaced by #818

**Pull request closed without merging**
