### PR TITLE
Replace "depends.txt" and "description.txt"...

### LINKED ISSUE #425: Use mod.conf, modpack.conf; remove deprecated counterparts
I actually did finish doing this, but I had targeted the wrong branch. Switching to the correct target branch resulted in conflicts throughout. And I did not have the patience to redo this whole thing again

P.S. @rubenwardy advised on using a bash script to do this.

EDIT: Clarified issue desc.

### PR DESCRIPTION
**Pull request by Panquesito7**
...with `mod.conf`.
Fixes #425.

There might be other commits that are merged here, but I would need to re-make everything again.
Please tell me if you find any naming-issue on `mod.conf` files.

### CODE REVIEW

**Comment by Panquesito7** [comment]
Ready for review.

**Comment by Panquesito7** [comment]
Reviewed, fixed some bugs (hopefully, it has no more bugs).
Should be done now.

**Comment by ClobberXD** [comment]
@Panquesito7 Deprecated method calls have already been fixed in `master` (see 85959ba9134c2b67de402f3ac8afd9de732600fc), and you can verify this by rebasing your PR on top of the latest master. So please revert the latest changes.

**Comment by ClobberXD** [comment]
All the deprecated function calls that have been left out are in `mods/pvp/shooter`, which will be removed soon and be replaced by a submodule - the PR is already open, see #439. So it's not worth fixing them. If you still really want to fix them, you should make a separate PR, as those changes are completely unrelated to this PR.

**Comment by ClobberXD** [comment]
> should I revert the changes editing file by file?

Not required. Here's a simpler technique:

- Open a terminal in the root dir of the repo.
- Reset to the latest good commit: `git reset --hard ac6e2a6`
- And force-push to remote: `git push -f`

**Comment by ClobberXD** [comment]
The maintenance part of this PR looks good to me :+1: 

Will approve, once the code changes are reverted.

**Comment by Panquesito7** [comment]
> > should I revert the changes editing file by file?
> 
> Not required. Here's a simpler technique:
> 
> * Open a terminal in the root dir of the repo.
> * Reset to the latest good commit: `git reset --hard ac6e2a6`
> * And force-push to remote: `git push -f`

Thank you, @ClobberXD.
I just have some questions:
- Do I need to install Git to do this?
- What do you mean with "opening a terminal"? Does this mean I need to do it via my PC, or the web?

_(You can perhaps mail me and answer these questions, as this is kinda getting off-topic.)_

**Comment by ClobberXD** [comment]
> Do I need to install Git to do this?

Hell yeah! ;)

> What do you mean with "opening a terminal"? Does this mean I need to do it via my PC?

Terminal == `cmd.exe` if you're on Windows. And yes you need to do this from your PC - GitHub just isn't equipped for anything but the simplest of operations.

****

I see you're not used to Git, and you only use GH's web interface. So the aforementioned steps to reset to a previous commit will be quite complicated for you. I'll do it myself, and update it to your branch.

**Comment by Panquesito7** [comment]
> I see you're not used to Git, and you only use GH's web interface. So the aforementioned steps to reset to a previous commit will be quite complicated for you. I'll do it myself, and update it to your branch.

Thank you very much for the assistance! 🙂
(BTW, I'm sorry for doing those commits: the ones which removes the old functions.)

**Comment by ClobberXD** [comment]
@Panquesito7: Please enable the "Allow edits by maintainers" checkbox, so that I have push access to the PR branch. See https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by Thomas--S** [comment]
_Offtopic:_ In case you are searching for an Minetest-related introduction to git, this might be interesting for you: https://forum.minetest.net/viewtopic.php?f=3&t=14262

**Comment by Panquesito7** [comment]
> @Panquesito7: Please enable the "Allow edits by maintainers" checkbox, so that I have push access to the PR branch. See https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Weird, it's already enabled.
I've deactivated it and activated it, hope that helps.

@ClobberXD, if that doesn't work, I'll add you as a collaborator on my fork.

**Comment by ClobberXD** [comment]
Nvm, still doesn't work.

The other changes look good, so I'll revert the extra commits and merge directly.

**Comment by Panquesito7** [comment]
> Nvm, still doesn't work.

Weird, okay. It has been activated since I created it.

> The other changes look good, so I'll revert the extra commits and merge directly.

Okay. Thank you, @ClobberXD. 👍

**Pull request closed without merging**
