### PR TITLE
Use voxel manip for barrier placing commands

### PR DESCRIPTION
**Pull request by a-blob**
- [x] This PR has been tested locally

### CODE REVIEW

**Comment by appgurueu** [comment]
Have you benchmarked that this is actually substantially faster? Barriers are a bit special because they are relatively sparse. VoxelManip can't offer sub-mapblock granularity. So with this PR, you'd be loading & setting at least 15 non-barrier blocks for each barrier block. This may very well offset any performance gains from using VoxelManip.

**Comment by a-blob** [comment]
The main problem with the current one is not speed, but that the barriers will have holes if a chunk within the selected area is not rendered yet.
image

**Review by LoneWolfHT — APPROVED** [review]
Is this ready and safe for merge?

**Comment by a-blob** [comment]
@LoneWolfHT I think so

**Pull request merged**
