### PR TITLE
Add C/A

### PR DESCRIPTION
**Pull request by moreavy**

### CODE REVIEW

**Comment by xenonca** [comment]
Please provide a proper description of what this PR does, it also adds an optional C/A requirement for the pro chest section.
I still believe that C/A will more likely discourage to even attempt to get the flag -> discourage capturing in general and doesn't really reflect any player skills.

**Comment by moreavy** [comment]
Capturing is EZ, and _**Pro Players**_ should be able to capture the flag in at least 4 attempts.

**Comment by Calinou** [comment]
I also think people should never be penalized for *attempting* to capture the flag, even if they always fail. Please don't encourage making the game campy :slightly_smiling_face:

**Comment by LoneWolfHT** [comment]
Closing as I'm only seeing self-support

**Pull request closed without merging**
