### PR TITLE
[Trivial] Enable crafting of powerful tools

### PR DESCRIPTION
**Pull request by ClobberXD**
- Allow crafting of axes and shovels from all ores.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Powerful shovels and axes are very useful at times, and they can't be compromised upon due to the lack of real estate.

**Comment by MinetestSam** [comment]
2 pages isn't a lot though

**Comment by ClobberXD** [comment]
If the order of registering crafts is preserved when displayed to the player, I could also re-order the registrations to ensure that the important crafts are on the first page.

**Comment by MinetestSam** [comment]
Yeah things like ladders and stone things and furnace could be moved to the 2 page

**Pull request merged**
