### PR TITLE
Make all players use the same smoke texture

### PR DESCRIPTION
**Pull request by appgurueu**
Uses a `dynamic_media_add`-based hack.

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
What does this look like when you use a transparent smoke texture?

**Comment by Lucyucy** [comment]
With a transparent smoke texture the smoke is invisible

**Comment by appgurueu** [comment]
> With a transparent smoke texture the smoke is invisible

Guess I'll have to throw in a `[noalpha` then...

**Comment by Lucyucy** [comment]
https://user-images.githubusercontent.com/80708819/118393319-dbfdc100-b63e-11eb-8f3f-8dabc2125499.png

Looks like this now

**Comment by appgurueu** [comment]
Alternative is just appending a `[makealpha` texture modifier. That works, but exposes ugly Minetest Z-sorting bugs. Would prefer this.

**Comment by DiamondPlane** [comment]
I tested it. Hmm, it looks now like this:
screenshot

**Comment by appgurueu** [comment]
> I tested it. Hmm, it looks now like this:
> screenshot

How it looks depends on the current smoke texture.

**Comment by appgurueu** [comment]
@savilli I don't see how this has become irrelevant.

**Comment by appgurueu** [comment]
> I don't think we should use a hack. If anything [6d5f046](https://github.com/MT-CTF/capturetheflag/commit/6d5f046d41c28e7243876f6ab349b0710ed51d22) approach should be used.

The mentioned approach is heavily limiting though.

**Pull request closed without merging**
