### PR TITLE
Fix healthbar HUD

### LINKED ISSUE #986: Bubbles overlap with hearts for knights
Bildschirmfoto von 2022-02-06 15-41-45

Knights have so much HP that their hearts overlap with the bubbles.

### PR DESCRIPTION
**Pull request by appgurueu**
Closes https://github.com/MT-CTF/capturetheflag/issues/979, closes #986

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
Shall I close in favor of an engine fix as discussed in Discord?

**Comment by appgurueu** [comment]
> Shall I close in favor of an engine fix as discussed in Discord?

If the engine gets a feature PR that allows implementing this slightly neater is merged, I will redo this.

**Comment by appgurueu** [comment]
Last commit closes #986 by right-aligning the hearts.
Bildschirmfoto von 2022-02-06 17-56-26
Bildschirmfoto von 2022-02-06 17-55-47

**Comment by appgurueu** [comment]
@savilli Bump. I see no reason not to merge this. Implementing a builtin feature would be significantly more work. This is now very clean and duplicates very little code (negligible). Pretty much everything that overrides the builtin defs has to duplicate just as much (small parts of the HUD element def). The only partially dirty thing I see is the use of the undocumented `register_on_playerevent` thing.

**Comment by savilli** [comment]
LGTM

**Comment by appgurueu** [comment]
@LoneWolfHT please review

**Pull request merged**
