### PR TITLE
Add map info to server status message

### PR DESCRIPTION
**Pull request by ClobberXD**
Adds map info to server status message, shown on player join and on using `/status` chat-command.

Targets dev5.0 branch.

### CODE REVIEW

**Comment by ClobberXD** [comment]
The engine feature has already been implemented, but it hasn't been released yet. Until 5.0.0 is out, this PR will remain WIP.

**Comment by ClobberXD** [comment]
PR now targets dev5.0 branch. Work's done, and PR's ready for testing and review.

**Comment by rubenwardy** [comment]
This is quite broken, needs a rebase

**Comment by ClobberXD** [comment]
Done, manually re-added all changes to latest master and force-pushed the branch. Ready to merge.

**Pull request merged**
