### PR TITLE
Change properties of the tools and swords

### PR DESCRIPTION
**Pull request by AKryukov92**
Changes according to calculation in the task #120

### CODE REVIEW

**Comment by rubenwardy** [comment]
mese could be weaker than diamond, but have a longer reach

**Comment by ClobberXD** [comment]
Add `range = <number>` to itemdef. This field is omitted from most item defs and therefore defaults to a range of 4 nodes.

**Comment by AKryukov92** [comment]
Maybe I should use #214 idea for mese to emphasise the fact that is has longer reach?
Mese sword will stay as it is. But in addition, there would be mese spear.

**Comment by AKryukov92** [comment]
I strongly suggest merging this PR without additional reach for mese tools and allow people to play-test it for a week.
I hope it solve a number of balance problems. Changing reach of mese tools is irrelevant right now.

**Comment by AKryukov92** [comment]
@rubenwardy what exactly should I do to get this PR merged?

**Comment by ClobberXD** [comment]
@AKryukov92 Would you be able to rebase this PR? Sorry for the delay in reviewing. I'll test this on my testing server after this has been rebased.

**Comment by LoneWolfHT** [comment]
You still around? This PR needs a rebase

**Pull request closed without merging**
