### PR TITLE
Convert shooter to git submodule

### LINKED ISSUE #383: Update shooter to latest version 0.6.1, targeting Minetest 5.0.0
`shooter` has gotten some major updates recently, including the use of Raycast for simplifying the code by leaps and bounds. So instead of just fixing the eye-height, I suggest we update `shooter` to v0.6.1, which is the version targeted at Minetest 5.0.0, IIRC.

### PR DESCRIPTION
**Pull request by ClobberXD**
Points to MT-CTF/shooter.

This also updates shooter to v0.6.1, which includes major changes in every area, like switching to a  raycast-based implementation, proper spread, real shotguns, etc.

Although not strictly required, I've replaced the now-deprecated gun names with the new ones. e.g.
`shooter:pistol` --> `shooter_guns:pistol_loaded`

Testing needed! Closes #383

### CODE REVIEW

**Comment by ClobberXD** [comment]
Put on hold due to the following bugs:

- stujones11/shooter#37
- stujones11/shooter#38

We'll have to wait for a 0.6.2

**Comment by ClobberXD** [comment]
shooter _seems_ to have stabilized. I'll finish this PR in a day or two.

**Comment by LoneWolfHT** [comment]
I've been using shooter as a submodule in my game. I've fixed (And made a PR for) all of the bugs I've found so far. Don't think there are any left

**Comment by ClobberXD** [comment]
Cool. Thanks! :)

**Comment by ClobberXD** [comment]
Finally fixed the de-sync issues with upstream, updated the submodule, and tested. Unfortunately, I encountered a bunch of bugs, and this PR can't be merged until those are fixed :(

**Comment by ClobberXD** [comment]
This PR has already been delayed by quite a bit. I suggest merging this as-is. The issues (they aren't even bugs per-se) once fixed, can be added to the submodule later.

This PR is ready for review.

**Comment by ClobberXD** [comment]
What the... I don't remember closing this. o_O

https://github.com/MT-CTF/capturetheflag/pull/398#event-2463755963 seems to have closed the PR automatically, as that force-push seems the revert all the changes. I'll look into it.

**Pull request closed without merging**
