### PR TITLE
Change the menu icon for CTF

### PR DESCRIPTION
**Pull request by MinetestSam**

### CODE REVIEW

**Comment by ClobberXD** [comment]
The texture seems to be very blurry, and doesn't look as crisp as the old one.

**Comment by MinetestSam** [comment]
> The texture seems to be very blurry, and doesn't look as crisp as the old one.
Yes, sadly no image editor allows you to rotate an image without it getting blurry.

**Comment by ClobberXD** [comment]
You're right, but this shouldn't be too difficult to do from scratch, IMO. The art style we follow makes it easier to re-create a texture from scratch, than to rotate it and fix the resulting blurriness.

**Comment by MinetestSam** [comment]
Rather than adding two flags should we just have 'Capture The Flag` in text?

**Comment by ClobberXD** [comment]
Nooooo, why would ya want dat? :/

**Comment by MinetestSam** [comment]
Realised how bad I was at drawing pixel art.... so closing the PR.

**Pull request closed without merging**
