### PR TITLE
Good news for miners: Mine to get score! 

### PR DESCRIPTION
**Pull request by Emojigit**
## Content of this PR
Mine these ores to get score!
- coal: 1 score
- gold and iron: 2 score
- diamond and mese: 3 score
## Why I do this
I become a miner (seldom kills) in "The Wall" and cleared a mine. But finally, I just get a few scores because I seldom kill. **THAT IS NOT FAIR!**
So, I work on this idea to help miners to get scores.

### CODE REVIEW

**Comment by winniepee** [comment]
Why would players should mine to get scores? Isn't this kinda weird?

**Comment by Emojigit** [comment]
> Why would players mine to get scores? Isn't this kinda weird?

In some maps, like "The wall", mining is an important part of playing. Miners provides minerals that can craft into generates, swords, guns, etc. If no miners then no win. But miners get no points!

**Comment by xenonca** [comment]
> Why would players should mine to get scores? Isn't this kinda weird?

Because this also helps your team win? Giving score for coal might be a bit too much but mining iron/mese/dia should indeed be rewarded IMO

**Comment by winniepee** [comment]
> > Why would players should mine to get scores? Isn't this kinda weird?
> 
> Because this also helps your team win? Giving score for coal might be a bit too much but mining iron/mese/dia should indeed be rewarded IMO

This will encourage players camping (And yeah, why coal should be included?)

**Comment by xenonca** [comment]
How will this encourage camping? You might want to get these ores anyway, the only difference is that you'll be rewarded for it. Once they're dug the points are gone anyway, no need to "camp" anymore.

**Comment by realOneplustwo** [comment]
Getting the ore is a reward in itself, point gain is not necessary.

**Comment by DiamondPlane** [comment]
I wouldn't do this or even if you'd add I recommend to make only if you dig mese and diamonds.

**Comment by DiamondPlane** [comment]
About gold: there no gold in CTF and even if there would be - you can't craft anything.

**Comment by appgurueu** [comment]
Code-wise not the way to go. Mod name is poorly chosen as well as group name. I'm not familiar with the API, but immediate `request_save()`? Sounds laggy.

**Comment by savilli** [comment]
I don't think we need that

**Comment by Emojigit** [comment]
I will rework that once I get a developer support. This PR will remain as a conversation.

**Comment by savilli** [comment]
No interest from core developers. Closing it for now, can be reopened later.

**Pull request closed without merging**
