### PR TITLE
Reduce lava flow range from 8 to 2

### PR DESCRIPTION
**Pull request by ClobberXD**
Goes a long way in preventing griefing...

Demonstration video: https://youtu.be/KYJvHJ8rxwk

### CODE REVIEW

**Comment by tidle** [comment]
sounds good

**Comment by rubenwardy** [comment]
I'm unsure on nuking lava like this, building lava moats is a valid defence technique

**Comment by ClobberXD** [comment]
When provided a sloping terrain, lava would still flow, but just not too much as it does now.

**Comment by ClobberXD** [comment]
As a player, I love this change, but on the other hand, it doesn't really make much sense to blame (and hence nerf) the lava, instead of tackling the root cause.

**Comment by MinetestSam** [comment]
I haven't really seen a lava moat being used in Caverns ever

**Comment by ClobberXD** [comment]
> I haven't really seen a lava moat being used in Caverns ever

Me neither - lava's always used by noobs to grief. But that doesn't mean we rob players of this viable defence system. Why I'm starting to get concerned about this PR is because this isn't the ideal solution to the problem of griefing, since it does not eliminate the root cause.

**Comment by LoneWolfHT** [comment]
I've seen quite a few lava moats. But the griefers always destroy it

**Comment by MinetestSam** [comment]
Hm well for a start why not decrease it to 5,6 or 7?

**Pull request merged**
