### PR TITLE
Add /s chat-command alias for /summary

### PR DESCRIPTION
**Pull request by ClobberXD**
Super-trivial. Tested; works.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Some have raised questions as to whether `/summary` is needed any more. I agree that `/summary` will never be used, because there's literally no difference between it and `/s`. Shall we remove it, or keep it for the sake of backwards-compat?

**Comment by Thomas--S** [comment]
I'd prefer to keep it. It will be easier to understand when players skim through the available chat commands with `/help`.

**Comment by ClobberXD** [comment]
Well, we've got random messages to help us with that. We could replace `/summary` with `/s` in that message. Also, `/help all` will list all commands along with their help text.

Currently, `/r` is linked to `/rankings` in only the random message, and the help texts of neither of these commands say anything about the other.

**Comment by ClobberXD** [comment]
Going by the current consensus, `/summary` is going to remain alongside `/s`. I'll consider this PR ready for merge.

**Pull request merged**
