### PR TITLE
Add support for per-map physics modifiers

### PR DESCRIPTION
**Pull request by ClobberXD**
Three new map meta fields are now available to map makers:

- `phys_speed`: Speed multiplier
- `phys_jump`: Jump multiplier
- `phys_gravity`: Gravity multiplier

### To test

- Add the following fields to the meta of your favourite map:
  ```
  phys_speed = <whatever>
  phys_jump = <yeah_yeah>
  phys_gravity = <meh>
  ```
- Play CTF, skip to the modified map. Observe that the modified physics roughly matches the values given in the meta.
- Skip to the next match. Observe that the physics values are back to normal.

Tested; works as expected.

### CODE REVIEW

**Comment by ClobberXD** [comment]
:notes: Bumpity-bump,
I'm sitting on a hump :musical_note:

**Comment by ClobberXD** [comment]
Rebased and re-tested

**Comment by JostP** [comment]
Maybe you can also supplement `Map_maker's` README.md with new lines for per-map physics modifiers in this PR?

**Comment by ClobberXD** [comment]
> Maybe you can also supplement Map_maker's README.md with new lines for per-map physics modifiers in this PR?

Will do; thanks for the suggestion.

**Pull request merged**
