### PR TITLE
Add reinforced cobble

### PR DESCRIPTION
**Pull request by ClobberXD**
Continued from #191 

Modified the recipe to allow players to craft reinforced cobble in any map with cobble itself. Recipe:
```
##
##

# = "default:cobble"
```

### CODE REVIEW

**Comment by ClobberXD** [comment]
Ah, thanks for pointing that out. Done.

**Comment by rubenwardy** [comment]
The point of the ingot is to make it more expensive to craft. Maybe iron isn't the best idea because it's so different on different maps

**Comment by ClobberXD** [comment]
> Maybe iron isn't the best idea because it's so different on different maps

Precisely. And cobblestone is just as easily available in all the maps. We _could_ just add back steel to the recipe and call it a day, and reinforced cobble would only be craftable (in large scale) on Caverns, but that doesn't feel right. Features should be independent from maps, and adding steel to the recipe would restrict rein. cobble to Caverns. Ideally it should be craftable on all maps, but _almost_ all maps is fine too.

**Comment by DS-Minetest** [comment]
Shouldn't it be a bit harder to build reinforced cobble? Like this you can easily craft much reinforced cobble in a short time and place it near the enemy base and the enemies can't easily stop you by killing you.
You could add a tool (maybe something like a reinforcement hammer) with that you have to dig the cobble (for about 5 seconds or so) to reinforce it which will also take cobble.

**Comment by DS-Minetest** [comment]
>I assume they have to crafted using ores

You could make them craftable with cobble:
```
ccc      c = cobble
csc      s = stick (or some cobble rod if there's no wood)
xsx      x = nothing
```

**Comment by AKryukov92** [comment]
I already said it in #191 and it worth repeating again.
What if we craft "raw reinforced cobble", which becomes "strong reinforced cobble" after 3 seconds.
Raw reinforced cobble should be gathered easily like dirt. Strong reinforced cobble should be harder than normal cobble and should not produce block on gathering.
This will be enough to build some fortification and in the same time, tunnelers will not be able to use it to block escape route.

**Comment by ClobberXD** [comment]
That is a very valid point. This would make it much more difficult to chase tunnellers.

The solution sounds complex and lag-inducing, though. We could use a global-step-based master timer, with one trigger for each individual node. Let's assume that a tunneller with the flag completely blocks the tunnel behind them with reinforced cobble. That would result in around a hundred triggers running at the same time, and will create some significant lag.

Also, 3s is too less for the raw form to set, as the more recently placed nodes will set before the chaser manages to break through. Increasing the time to set means that even more triggers would run at the same time.

**Comment by AKryukov92** [comment]
What about "reinforcing" raw blocks by jumping on them?
This type of action is very uncommon for tunnelers. They usually dig 2x1 tunnels and will be unable to just jump over raw cobble to reinforce it.
In the same time, builders can easily jump over walls of their fortifications.

**Comment by DS-Minetest** [comment]
The raw reinforced cobble needing time to become hard after some time is an interesting idea. It's like liquid concrete becoming hard by drying.

Jumping on it won't work easily, there's no callback for it.
I think the best is to simply use an abm.
(Globalstep / core.after won't work for unloaded nodes. Node timers don't make sense for many nodes. Abm can also have a chance, so it won't become hard in the order it was placed.)

Should raw reinforced cobble be faster digable than cobble? (Maybe group `crumbly = 4` and add for `crumbly = 4` a fast time in wieldhand (faster than for `crumbly = 3`).
Raw reinforced cobble could also be made falling.

**Comment by rubenwardy** [comment]
This is currently uncraftable

**Comment by ClobberXD** [comment]
Fixed and tested. It takes ~ 2.5s to dig using steel pick.

**Comment by ClobberXD** [comment]
Rebased. Does the use of reinforced cobble by tunnellers really count as abuse? If so, should I add a raw variant of reinforced cobble that only sets after a couple of seconds?

**Pull request merged**
