### PR TITLE
Add translation strings to descriptions

### PR DESCRIPTION
**Pull request by An0n3m0us**
Ref: #476 

Using a script, I've changed the descriptions to a format to make them possible for translating.

I couldn't test it as I couldn't load the subgame; it's giving this error after I make a map and try and start it:
`ctf/ctf_map/ctf_map_core/schem_map.lua:1: singlenode mapgen is required.`

### CODE REVIEW

**Comment by MinetestSam** [comment]
> I couldn't test it as I couldn't load the subgame; it's giving this error after I make a map and try and start it:
> `ctf/ctf_map/ctf_map_core/schem_map.lua:1: singlenode mapgen is required.`

While creating a new world make sure to select 'singlenode' as the map-gen as CTF runs only on that.

**Comment by An0n3m0us** [comment]
Oh, thanks!

**Comment by ClobberXD** [comment]
Firstly, thanks for working on this. 

Secondly, I'm not very familiar with client-side translations and how they're implemented, so it'd probably be @rubenwardy or @Thomas--S who's going to be giving the final approval. But I am interested in testing this though. How do I test this, and what are the things I need to do to verify that this PR works?

**Comment by An0n3m0us** [comment]
That's fine; I'm kinda new to it too.

<br>

Lets say we wanted to translate the bandage description:

`S("Bandage, heals teammates for 3-4 HP until HP is equal to @1", healing_limit)`

@1 just represents the variable `healing_limit`. We can use @2 to represent another variable, like this:

`S("Bandage, heals teammates for @2 HP until HP is equal to @1", healing_limit, heal_amount)`

<br>
<br>

Anyway, one can create a folder called `locale` in the `ctf_bandages` mod, then create a file called `ctf_bandages.fr.tr` if they wanted to translate to French.

Then, one would edit the file and put something like this:

```
#textdomain: ctf

Bandage, heals teammates for 3-4 HP until HP is equal to @1 = Xxx @1
```

(`ctf` represents the modpacks name)

Now, if you set the Minetest language to French and get a bandage, it will read `Xxx 15` (because `15` is the value that the `healing_limit` variable is currently set to.

**Comment by ClobberXD** [comment]
Interesting, thanks for explaining how this works! I'm a little short on time at the moment, but I'll try to _start_ testing this within this month.

**Comment by Panquesito7** [comment]
The `locale` folder is needed in each mod, and the files (`ctf.es.tr` or whatever language) are needed.

**Comment by ClobberXD** [comment]
This PR just adds support for client-side translations and doesn't add the translations themselves. Is the locale dir (with all the files) required for this?

**Comment by An0n3m0us** [comment]
No; it's not required. All I've done is put in place the translation strings; the locale directory and files is for the actual translations.

**Comment by ClobberXD** [comment]
Ok, good to know, thanks for clarifying

**Comment by rubenwardy** [comment]
I glanced through, and the approach here looks correct

**Comment by An0n3m0us** [comment]
That can easily be removed if needed.

**Comment by rubenwardy** [comment]
I suspect that the common was copied from MT game.  This is not adding support for MT game translation, this is adding support for CTF translation. The comment doesn't add anything anyway

**Pull request closed without merging**
