### PR TITLE
Improve vote_kick mechanism

### PR DESCRIPTION
**Pull request by MinetestSam**
Starting and/or participating in vote_kick requires a special vote_trusted priv.
Thanks to ClobberXD

### CODE REVIEW

**Comment by rubenwardy** [comment]
vote_kick is better

**Comment by ClobberXD** [comment]
I assume this PR is about creating a new dedicated priv for the `vote_kick` voteset, and `vote_kick` sounds good.

**Comment by MinetestSam** [comment]
> vote_kick is better

Well you wouldn't want noobs to kick anyone though as they will just type yes

**Comment by MinetestSam** [comment]
So what about the idea of giving trusted players a trusted privs which would allow them to start a vote kick?

**Comment by AKryukov92** [comment]
I agree with rubenwardy: everyone should be allowed to vote.
Only some should be allowed to start such vote.
Voting should be logged to give mods some evidence about possible abuse of this feature.

**Pull request closed without merging**
