### PR TITLE
Consider captures as a requirement for pro players

### PR DESCRIPTION
**Pull request by MinetestSam**
Closes: #525

### CODE REVIEW

**Comment by ClobberXD** [comment]
Fixed merge conflict. Unless someone's playing during the dead hours, I think 20 might be a bit too much. I say we start with 10, and increase it if necessary.

**Comment by MinetestSam** [comment]
> Unless someone's playing during the dead hours, I think 20 might be a bit too much. I say we start with 10, and increase it if necessary.

Yeah I also think this is a hit and trial process and we will only be able to determine the correct value after several tests

**Comment by ClobberXD** [comment]
10 seems reasonable at first glance, but I'd prefer to test this before actually approving. Also, marking this PR as low priority as this won't be a part of 2.0.0 as we've earlier discussed.

**Comment by fjmng** [comment]
The formspec to unlock the pro section of the chest and the random messages should be updated

**Comment by ClobberXD** [comment]
@fjmng Please continue this discussion in #541, as this PR has been closed.

**Pull request closed without merging**
