### PR TITLE
Restore register_on_killedplayer callback in ctf_stats

### PR DESCRIPTION
**Pull request by savilli**
kill assist system shouldn't affect player kill stats

### CODE REVIEW

**Comment by savilli** [comment]
Fix https://github.com/MT-CTF/capturetheflag/issues/789

**Comment by Panquesito7** [comment]
> Fix #789

Please add this in the PR comment, not in another comment, otherwise it won't work.

**Comment by savilli** [comment]
> > Fix #789
> 
> Please add this in the PR comment, not in another comment, otherwise it won't work.

WHYM? It's linked

**Comment by savilli** [comment]
> > Fix #789
> 
> Please add this in the PR comment, not in another comment, otherwise it won't work.

WDYM? It's linked

**Comment by Panquesito7** [comment]
Nope.
Linked issues (none yet)

**Comment by LoneWolfHT** [comment]
I guess this would be a good idea. Although it won't fully fix the linked issue, score still wouldn't be awarded

**Pull request merged**
