### PR TITLE
Remove all unused MTG features - Part 2

### PR DESCRIPTION
**Pull request by ClobberXD**
Removes the following:

- Saplings and corresponding growth functions and node-timers.
- Features using node meta (e.g. bookshelves formspec)
- Signs (meaningless without node-meta, so removed them altogether)

****

High priority bugfix, as this fixes the crash on sapling place. But this requires a lot of testing before merge to ensure nothing else is broken.

### CODE REVIEW

**Comment by rubenwardy** [comment]
How about removing saplings?

**Comment by Thomas--S** [comment]
I also support removing the saplings. They were absent before 5.0, too, if I remember correctly.

**Comment by ClobberXD** [comment]
Sapling were present before 5.0.0 as well. But I'll remove it; good idea.

**Comment by Thomas--S** [comment]
> Sapling were present before 5.0.0 as well.

I didn't find them in the following file: https://github.com/MT-CTF/capturetheflag/blob/5daefadc7e8e3a0982fa012fd7544f43fa4ecba7/mods/mtg/default/nodes.lua

**Comment by ClobberXD** [comment]
That's strange. Saplings were probably removed in the process of updating to 5.0.0, but got re-added with MTG 5.0.0. See https://github.com/MT-CTF/capturetheflag/blob/947715fbe80c715dd76b87105a470e998cc7a86d/mods/mtg/default/nodes.lua#L666

**Comment by Thomas--S** [comment]
The saplings were removed on 27th of January 2018 by rubenwardy:

https://github.com/MT-CTF/capturetheflag/commit/ddc9d88a03616b94338c7ba266788424b07f5240#diff-4c0fc0806e6a443774cea3aea5f3febeL592

**Comment by ClobberXD** [comment]
Removed all saplings.

**Pull request merged**
