### PR TITLE
Fix bug - Poison grenades deal no damage to enemies.

### PR DESCRIPTION
**Pull request by mrtechtroid**
- [x] This PR has been tested locally
- Due to damage amount being very low, `1` instead of `10`, the poison grenade did not do damage at all to players. 
- Caused due to PR f847ac8

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
That's punch_interval, the damage is down where `fleshy=1` is. Maybe that needs to be increased to 2? A punch interval of 1 should be fine

**Comment by mrtechtroid** [comment]
It does work(does damage as expected), when the punch_interval was increased to 10. However could you let me know of any alternative approaches to fix it.

**Comment by farooqkz** [comment]
hmm it works

**Review by farooqkz — APPROVED** [review]
works

**Comment by LoneWolfHT** [comment]
> It does work(does damage as expected), when the punch_interval was increased to 10. However could you let me know of any alternative approaches to fix it.

There might be an on_punchplayer or something that's ignoring 1hp damage with punch intervals of 1

What does 2hp of fleshy damage do?

**Comment by mrtechtroid** [comment]
Yes, punch interval 1, with fleshy = 2 also works, in fixing the issue.

**Pull request merged**
