### PR TITLE
User-Defined Bounty

### PR DESCRIPTION
**Pull request by arihant2math**
- [x] This PR has been tested locally

Adds a `/bounty` command that allows player to bounty others of their choice. There is a 5 minute timer before the player can set another bounty.

### CODE REVIEW

**Comment by arihant2math** [comment]
image

**Comment by farooqkz** [comment]
Thank you so much for contributing to CTF. But there is already a PR here: https://github.com/MT-CTF/capturetheflag/pull/1112

**Comment by LoneWolfHT** [comment]
Yeah, you could look over their code to see if they did anything better than you though

**Comment by arihant2math** [comment]
That PR has been inactive for almost a year ...

**Comment by LoneWolfHT** [comment]
Until a PR is closed it's still valid, and you should talk with the author of it before starting your own. Sorry for the confusion

**Pull request closed without merging**
