### PR TITLE
Add shotgun to disallowed items for knights

### PR DESCRIPTION
**Pull request by Lucyucy**
Every gun should be restricted to shooters except for the pistol. This revalues and balances the shooter class a bit better.

### CODE REVIEW

**Comment by RyanZem** [comment]
> Every gun should be restricted to shooters except for the pistol. This revalues and balances the shooter class a bit better.

so knights won't have any cool weapon to use then ?

**Comment by savilli** [comment]
No interest from core developers. Closing it for now, can be reopened later.

**Comment by magnetar47** [comment]
Re-opened after long discussion on Discord. Concept has core dev approval now.

**Comment by magnetar47** [comment]
Marking as controversial, as this was heavily downvoted in past polls.

**Comment by farooqkz** [comment]
There are two things:

 - Those who disagree don't want to remove the fun. A knight has a sword and no one else in classes mode can have a sword or use it. A knight with shotgun is just OP so why remove the joy of almost endless kills?
 - Those who agree try to introduce balance to the game.

**Comment by magnetar47** [comment]
Also, I think many people who _want_ knights to have shotguns, may not have been on the receiving end much. :P

**Comment by farooqkz** [comment]
No decision about this yet?

**Comment by farooqkz** [comment]
@Lucyucy TBH, I am against knights having shotgun.

**Pull request closed without merging**
