### PR TITLE
Make the door's window more wider

### PR DESCRIPTION
**Pull request by winniepee**
screenshot_20210123_163229
The screenshot is an example for the textures.

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
Why?

**Comment by moreavy** [comment]
We may not need them

**Comment by Toby1710** [comment]
It doesn't look very nice... The texture that is now better.

**Comment by moreavy** [comment]
The team doors in ctf refer to the original `steel door` in the Minetest Game. Make Pull in the [Minetest Game Repository](https://github.com/minetest/minetest_game) instead of this one.

**Comment by winniepee** [comment]
> It doesn't look very nice... The texture that is now better.

I am OK with that, I already knew this will fail.

**Comment by winniepee** [comment]
> We may not need them. If you need so.. change your textures
> 
> ```
> But if you change your textures.. only you may be able to hit bypass the doors while others  wouldn't.
> ```

The textures doesn't affect anything at all

Texture = texture
Node = node

Anyone can hit bypass the doors because of the bug issues, not the textures.

**Comment by moreavy** [comment]
> > We may not need them. If you need so.. change your textures
> > ```
> > But if you change your textures.. only you may be able to hit bypass the doors while others  wouldn't.
> > ```
> 
> The textures doesn't affect anything at all
> 
> Texture = texture
> Node = node
> 
> Anyone can hit bypass the doors because of the bug issues, not the textures.

Read https://github.com/MT-CTF/capturetheflag/pull/762#issuecomment-766717018

> The team doors in ctf refer to the original `steel door` in the Minetest Game. Make Pull in the [Minetest Game Repository](https://github.com/minetest/minetest_game) instead of this one.

**Comment by LoneWolfHT** [comment]
> The team doors in ctf refer to the original `steel door` in the Minetest Game. Make Pull in the [Minetest Game Repository](https://github.com/minetest/minetest_game) instead of this one.

We don't follow latest MTG. It's best made here

**Comment by moreavy** [comment]
Btw why do we need to make door's windows wider? What's the need @winniepee ?

**Pull request closed without merging**
