### PR TITLE
Add Spanish translations where applicable

### PR DESCRIPTION
**Pull request by Panquesito7**
Things added/changed:

- Add Spanish translations where applicable.

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
Espero haber encontrado todo lo que se puede corregir 👍

**Comment by LoneWolfHT** [comment]
I'll merge this next rebase unless @LuismiInTheZone has suggestions to make

**Comment by LuismiInTheZone** [comment]
@LoneWolfHT Fixes weren’t done yet…

**Comment by LoneWolfHT** [comment]
Oh, that wasn't obvious from looking at the comment history. I was clearing out my aged Github queue.

**Comment by LuismiInTheZone** [comment]
> Oh, that wasn't obvious from looking at the comment history. I was clearing out my aged Github queue.

Ok don’t worry, I’ll create a PR later so you can merge it 👍

**Pull request merged**
