### PR TITLE
Adding 2*7 slots to teamchest

### PR DESCRIPTION
**Pull request by farooqkz**
screenshot_20221211_152953

I thought 14 more slots are enough and there is no need to double it.

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
Everything seems fine, just needs to get an approval from some mod

**Comment by LoneWolfHT** [comment]
You should make the formspec wider to account for the addition. Not sure how that will work on smaller screens though

**Comment by LoneWolfHT** [comment]
Note #1032

**Comment by farooqkz** [comment]
Solved 
screenshot_20221212_161623

**Pull request merged**
