### PR TITLE
allow donating maximum score by donating 0 or less

### PR DESCRIPTION
**Pull request by lazylier**
- [x] This PR has been tested locally

[Suggestion](https://discord.com/channels/447819017391046687/1008040841102766153/1288113654742519838)

This should allow players to donate half their score by using 0 or any negative number as the donation amount. I've tested it as well as I can.

### CODE REVIEW

**Comment by farooqkz** [comment]
Hello! Nice doing. However I don't like using `0` or negative numbers for this. I would prefer `max` for this. like `/donate LandarVargan max` to donate the maximum amount you can donate. I will review code after you've changed this. Cheers!

**Comment by lazylier** [comment]
> Hello! Nice doing. However I don't like using `0` or negative numbers for this. I would prefer `max` for this. like `/donate LandarVargan max` to donate the maximum amount you can donate. I will review code after you've changed this. Cheers!

That would be more complicated since you'd have to also check if 'max' is a player name and figure out how to handle that

**Comment by farooqkz** [comment]
Maybe `:max`?

**Comment by LoneWolfHT** [comment]
I'm fine with either method, although 0 shouldn't turn into the max amount

**Comment by lazylier** [comment]
now it should take :max or negative numbers, and I added a line to the description explaining that

**Comment by farooqkz** [comment]
Code looks good to me.

**Review by LoneWolfHT — APPROVED** [review]

**Pull request merged**
