### PR TITLE
Medkits: Don't give back if map is skipped

### PR DESCRIPTION
**Pull request by appgurueu**

### CODE REVIEW

**Comment by savilli** [comment]
ctf.register_on_new_game?

**Comment by appgurueu** [comment]
> ctf.register_on_new_game?

on_new_match I think, but thanks for the pointer! Should have read the docs.

**Comment by savilli** [comment]
> > ctf.register_on_new_game?
> 
> on_new_match I think. Thanks for the pointer! Should have read the docs.

Currently it's the same but on_new_match makes more sense indeed

**Comment by savilli** [comment]
ctf_match.register_on_new_match

**Pull request merged**
