### PR TITLE
Minor Bugfix of add reason to medkit

### PR DESCRIPTION
**Pull request by Emojigit**

### CODE REVIEW

**Comment by Emojigit** [comment]
Fix https://github.com/MT-CTF/capturetheflag/pull/729 's minor bug

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Needs rebase.

**Comment by Emojigit** [comment]
> Needs rebase.

Fixed

**Comment by Emojigit** [comment]
> Needs rebase.

@Panquesito7 Fixed

**Review by Panquesito7 — APPROVED** [review]
LGTM. Thanks for your contribution! 🎉 👍

**Pull request merged**
