### PR TITLE
Prevent item's special ability from activating during build time.

### PR DESCRIPTION
**Pull request by mrtechtroid**
- [x] This PR has been tested locally
- Based on suggestion [Discord](https://discord.com/channels/447819017391046687/1008040841102766153/1225663529756131370), now prevent users from activating diamond sword/granade/invincible mode during build time.

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
It'd probably be a good idea to add a HUD message saying you can't activate during build time. So as not to confuse new players trying to figure out abilities

**Review by farooqkz — CHANGES_REQUESTED** [review]
Based on DRY rule, I suggest defining a new function somewhere and calling it from the 3 places.

**Comment by LoneWolfHT** [comment]
I'm fine merging it without, up to techdroid

**Comment by mrtechtroid** [comment]
Im fine with merging too. if its not a big issue.

**Pull request merged**
