### PR TITLE
Automatically close doors

### PR DESCRIPTION
**Pull request by AKryukov92**
This is result of dicsussion of #181

### CODE REVIEW

**Comment by Thomas--S** [comment]
I think that this is not a very good idea because of this two reasons:

1) An additional ABM will introduce lag.

2) (and this is the more important point) Image the following: Some noobs like to build a base like this:

```
    C D C
    C D C
    C D C
C C C D C C C
C           C
C           C
C     F     C
C           C
C     T     C
C C C C C C C


C = Cobblestone
D = Door
F = Flag
T = Team chest
```

It would be very annoying and a tactical disadvantage, if all these doors are closed automatically all the time.

**Comment by AKryukov92** [comment]
Why do you express your opinion only now, then work is already done, tested and prepared to be merged? Issue #181 was hanging there for half of the year. I described this change two months ago.

1. Any change can introduce lag. It is not the reason to deny feature.
This feature will not introduce lag because there are only a few doors in the game. Each one sends only 1 update every second. Simple player combat generates much more lags than this.
2. If some noobs can build bad base, then it is the problem of noobs. They always build strange constructions, which only annoy me. What do the doors have to do with it?

**Comment by AKryukov92** [comment]
0. Who knows. This feature was implemented and I very disappointed that you are trying to deny my work.

1. Any suggestion how to make it better?

2. I think that doors should be kept close. Having straight open way to the flag is bad idea.
Base should be designed to quickly leave but hardly to enter. Doors is the simplest option to do it.
Noobs are always the problem of pro players. Should we disable their ability to place blocks then?
This will be a great *advantage* when trying to *protect* a flag bearer of the *your* team.

3. I agree with this, but what do the doors have to do with it? Should we remove doors altogether because "they don't add defence"?

**Comment by Thomas--S** [comment]
0) A PR is not a guarantee to get it merged. It is a suggestion, which will then be discussed and eventually either accepted or rejected.

1) Node timers might be a little bit better.

2) Leaving the doors open is usually not a bad idea, as you can close them when enemies approach.
Leaving doors open is also essential when trying to fight the flag bearer and your team is the weaker one.

3)
> but what do the doors have to do with it?

> So leaving a door open won't be too problematic.

**Comment by AKryukov92** [comment]
0. I would be less disappointed if this feature was denied at the time of discussion in Issues, than now. I spent some time to find solution, to test it and you have awoken now and trying to argue.

1. I'll look at node timers.

2. I don't really want to watch out for approaching enemy just to close the doors for them.

3. It is only your *late* opinion. ClobberXD and CLtheman1 and me liked the idea of automatically closable doors.

**Comment by rubenwardy** [comment]
This should be done using node timers (if it is to be done at all, worth discussing that first)

**Comment by AKryukov92** [comment]
If it is worth dicsussing, what is your arguments?

**Comment by ClobberXD** [comment]
@AKryukov92 You're work is much appreciated, but auto-closing doors isn't suitable for CTF (see above comments for "why?") and certainly isn't worth the extra checks and timers (better than ABMs but still more intensive than not having it at all). So closing.

**Pull request closed without merging**
