### PR TITLE
Add respawn_timer

### PR DESCRIPTION
**Pull request by appgurueu**
Uses a submodule. Minor inconvienences might need to be addressed (health bar & nametag).

### CODE REVIEW

**Review by Panquesito7 — COMMENTED** [review]
This mod depends on the `modlib` mod, and `modlib` is not present here.

**Comment by appgurueu** [comment]
> This mod depends on the `modlib` mod, and `modlib` is not present here.

Indeed

**Comment by LoneWolfHT** [comment]
This would be better done as a quick, fast, and simple mod that is intended for CTF only

**Comment by LoneWolfHT** [comment]
I've done what I suggested. I'll push it once my computer has internet.
Sorry for closing but there's a bit too much in this. Despite that I have used some of your ideas in my version. So this wasn't a complete waste :P

**Pull request closed without merging**
