### PR TITLE
Add cobble, wood, torches and team door to the team chest

### PR DESCRIPTION
**Pull request by RyanZem**
(there no ctf_traps mod so I can't add it)

### CODE REVIEW

**Comment by RyanZem** [comment]
> Why?

Many players want it and it was suggested. The reason is that we can build our base by not even trying to find something in treasure chests, just by opening the team chest. It's actually a PR so it's ok if you don't want to merge it. :)

**Comment by savilli** [comment]
> > Why?
> 
> Many players want it and it was suggested. The reason is that we can build our base by not even trying to find something in treasure chests, just by opening the team chest. It's actually a PR so it's ok if you don't want to merge it. :)

Where was it suggested?

**Comment by RyanZem** [comment]
> > > Why?
> > 
> > 
> > Many players want it and it was suggested. The reason is that we can build our base by not even trying to find something in treasure chests, just by opening the team chest. It's actually a PR so it's ok if you don't want to merge it. :)
> 
> Where was it suggested?

here: https://discord.com/channels/447819017391046687/448136308108296213/917840446011613184 but I already coded it before it was suggested.

**Comment by appgurueu** [comment]
Not happy with the current state of this:

1. Should be configurable, not "hardcoded"
2. Why did you put that in the code, at that place? Where is it handled currently?

**Comment by savilli** [comment]
We've decided it should be per-mode

**Review by savilli — CHANGES_REQUESTED** [review]
We've decided it should be per-mode

**Comment by savilli** [comment]
Closed in favor of 9f0186e8bf9f81a208a727cc90dd01ae1b1e42ff

**Pull request closed without merging**
