### PR TITLE
Victory score

### PR DESCRIPTION
**Pull request by lazylier**
This has been suggested a few times I think, most recently [here.](https://discord.com/channels/447819017391046687/448136308108296213/1135090580272205874) Each player on a winning team gets score based on how many points he's contributed to that team relative to everyone else.

### CODE REVIEW

**Comment by farooqkz** [comment]
I am very doubtful about this. Regarding the incentive you are proposing, it is still to advantage of a player to let their teammate who has the flag die. Because when the player themselves cap, they will get this "victory score" *and* capture score.

**Comment by lazylier** [comment]
> Because when the player themselves cap, they will get this "victory score" _and_ capture score.

That is not how it's supposed to work. You only get the victory score if you didn't capture.

**Comment by farooqkz** [comment]
> > Because when the player themselves cap, they will get this "victory score" _and_ capture score.
> 
> That is not how it's supposed to work. You only get the victory score if you didn't capture.

oh so I misunderstood. But still, it's not a good incentive IMO for the reasons I will explain later.

**Comment by 165135** [comment]
> > > Because when the player themselves cap, they will get this "victory score" _and_ capture score.
> > 
> > 
> > That is not how it's supposed to work. You only get the victory score if you didn't capture.
> 
> oh so I misunderstood. But still, it's not a good incentive IMO for the reasons I will explain later.

@farooqkz Could you elaborate on your reasoning? Just curious.

**Comment by farooqkz** [comment]
I don't exactly remember my reasons, now. And after reading your code, I think it's fine  and a good addition to the game :)

**Comment by 165135** [comment]
@LoneWolfHT Was this supposed to be added after the reset?

**Pull request merged**
