### PR TITLE
Add translations (and zh_TW)

### PR DESCRIPTION
**Pull request by Emojigit**
- [x] ctf
- [x] ctf_alloc
- [x] ctf_bandages
- [x] ctf_bounties
- [x] ctf_chat
- [ ] ctf_classes
- [ ] ctf_colors
- [ ] ctf_crafting
- [ ] ctf_events
- [ ] ctf_flag
- [ ] ctf_inventory
- [ ] ctf_leave_message
- [ ] ctf_map
  - [ ] ctf_map_core
  - [ ] map_maker
- [ ] ctf_marker
- [ ] ctf_match
- [ ] ctf_metrics
- [ ] ctf_otherteams
- [ ] ctf_playertag
- [ ] ctf_reports
- [ ] ctf_respawn_delay
- [ ] ctf_respawn_immunity
- [ ] ctf_stats
- [ ] ctf_traps
- [ ] ctf_treasure
- [ ] ctf_userlimit
- [ ] afkkick
- [ ] crafting
- [ ] darkness_nerf
- [ ] email
- [ ] give_initial_stuff
- [ ] hud_events
- [ ] hudkit
- [ ] hud_score
- [ ] latest_updates
- [ ] lib_chatcmdbuilder
- [ ] no_minimap
- [ ] physics
- [ ] random_messages
- [ ] real_suffocation
- [ ] sprint
- [ ] treasurer
- [ ] tsm_chests
- [ ] vote
- [ ] wield3d
- [ ] anticoward
- [ ] dropondie
- [ ] gauges
- [ ] grenades
- [ ] hpregen
- [ ] kill_assist
- [ ] medkits
- [ ] modpack.conf
- [ ] place_limit
- [ ] shooter
- [ ] shooter_tweaks
- [ ] sniper_rifles

### CODE REVIEW

**Comment by ksandronline** [comment]
for add translate need do fork from "Emojigit:fork-20210709-trans+zh" and commit there?

**Comment by Panquesito7** [comment]
> for add translate need do fork from "Emojigit:fork-20210709-trans+zh" and commit there?

You would have to create a pull request in their fork. You should let them know so they can merge it. 🙂

**Comment by LoneWolfHT** [comment]
Oh nice.
Could you put this on hold until 3.0 is merged? Or make a PR to it instead? https://github.com/LoneWolfHT/capturetheflag/tree/3.0

**Comment by Emojigit** [comment]
> Oh nice.
> Could you put this on hold until 3.0 is merged? Or make a PR to it instead? https://github.com/LoneWolfHT/capturetheflag/tree/3.0

Make a PR to it instead since the changes here may not be compatible with v3

**Comment by LoneWolfHT** [comment]
> Make a PR to it instead since the changes here may not be compatible with v3

Yeah

**Pull request closed without merging**
