### PR TITLE
Make stealing from enemy teamchest(s) possible while they are open

### PR DESCRIPTION
**Pull request by farooqkz**
Issue: #1058 

I'm working on it. Currently the algorithm is as such:
 - Keep a list of players who have opened the teamchest in `openers`(in `mods/ctf/ctf_modes/ctf_modes_classic/init.lua`)
 - Remove the player on death or leave
 - Check every 2 seconds using `minetest.after()`, if more than 5 seconds has been elasped, remove the player from `openers`
 - if length of `openers` is zero, the chest is closed

Meanwhile I'm working on it, you can check if the sound clip I've used for stealing alarm is good.

### CODE REVIEW

**Comment by farooqkz** [comment]
It's ready. Please someone tell me how to make luacheck happy :)

**Comment by LoneWolfHT** [comment]
Global functions must go in their mod's namespace table

**Comment by farooqkz** [comment]
> Global functions must go in their mod's namespace table

May you give an example how?

**Comment by LoneWolfHT** [comment]
The ctf_teams namespace table is `ctf_teams`, global functions are put in that table (`ctf_teams.get_team()`, etc)

**Comment by LoneWolfHT** [comment]
You commited changes to the map submodule again.

Try running
```bash
cd capturetheflag/mods/ctf/ctf_map/maps/
git remote update
git checkout origin/master
cd ../../../..
git status
```
and showing the output of that last `git status` (You will need to edit the cd command's path for it to work)

**Comment by farooqkz** [comment]
> You commited changes to the map submodule again.
> 
> Try
> 
> ```shell
> cd capturetheflag/mods/ctf/ctf_map/maps/
> git remote update
> git checkout origin/master
> cd ../../../..
> git status
> ```
> 
> and showing the output of that last `git status` (You will need to edit the cd command's path for it to work)

I will do it when I have the stealing feature done.

**Comment by MrRar** [comment]
I think it should be easier than that to steal from the enemy chest. I think if you can get all the way into the enemy base you should be able to take whatever you want from the team chest even if no one is currently in it.

**Comment by farooqkz** [comment]
> I think it should be easier than that to steal from the enemy chest. I think if you can get all the way into the enemy base you should be able to take whatever you want from the team chest even if no one is currently in it.

I disagree. As a player I know that getting to enemy teamchest is not that hard.

**Comment by farooqkz** [comment]
To make it even more challenging I propose this:

 - An enemy must hit the teamchest to steal something from it
 - Upon hitting, the game chooses a slot randomly and adds its item to the hitter inventory. The chosen slot might be possibly empty
 - The teamchest screams anyway even if it's closed or no item was stolen(or in other words, an empty slot was randomly chosen).

Opinions?

**Comment by tigercoding56** [comment]
> I think it should be easier than that to steal from the enemy chest. I think if you can get all the way into the enemy base you should be able to take whatever you want from the team chest even if no one is currently in it.

yes

**Comment by tigercoding56** [comment]
> To make it even more challenging I propose this:
> 
>     * An enemy must hit the teamchest to steal something from it
> 
>     * Upon hitting, the game chooses a slot randomly and adds its item to the hitter inventory. The chosen slot might be possibly empty
> 
>     * The teamchest screams anyway even if it's closed or no item was stolen(or in other words, an empty slot was randomly chosen).
> 
> 
> Opinions?

no   if a player has made it into the enemies base they should be able to quickly take their loot (else they will just take the flag and leave)

**Comment by farooqkz** [comment]
I still disagree. Getting to enemy base unnoticed is usually very easy if you spend enough time.

**Comment by farooqkz** [comment]
Closing in favor of https://github.com/MT-CTF/capturetheflag/pull/1321

**Pull request closed without merging**
