### PR TITLE
Restore old grenade textures

### PR DESCRIPTION
**Pull request by a-blob**
Restore previous grenade textures and names before the Xmas event. I kept the Xmas textures so they can be easily switched back.

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
I don't know if you did this because my suggestion but I meant another thing... I told this to Landar long time ago and he said that there were more important things to do #1094

**Comment by tigercoding56** [comment]
i agree

**Comment by a-blob** [comment]
Oops. Probably shouldn't go around renaming branches.

**Comment by a-blob** [comment]
I'll just leave this closed for now.

**Pull request closed without merging**
