### PR TITLE
Colorize "flag regarding" messages

### PR DESCRIPTION
**Pull request by JostP**
Old:
Zaslonska slika 2020-12-09 11-27-58

New:
Zaslonska slika 2020-12-09 09-54-32

### CODE REVIEW

**Comment by Thomas--S** [comment]
I'm not sure, but I think that CTF (at least the engine) also supports additional colors. Maybe a more abstract implementation that uses the colors from the ctf_pvp_engine would be possible?

**Comment by JostP** [comment]
> I'm not sure, but I think that CTF (at least the engine) also supports additional colors. Maybe a more abstract implementation that uses the colors from the ctf_pvp_engine would be possible?

Maybe you mean this file? I got colors for text here. But I am not sure that I am that expert to understand what I should change.

**Comment by LoneWolfHT** [comment]
`red` is probably an unknown variable. Should make that a string

**Comment by JostP** [comment]
> `red` is probably an unknown variable. Should make that a string

I tried with:

```
flag_return_color = ctf_colors.colors(red)
flag_return_color = ctf_colors.colors("red")
flag_return_color = ctf_colors(red)
flag_return_color = ctf_colors("red")
flag_return_color = ctf_colors.colors[1]
flag_return_color = ctf_colors.colors["1"]
```

and I have been getting crashes every time. Current solution works and I see no need to complicate it.

**Comment by Thomas--S** [comment]
`ctf_colors.colors["red"]` and `ctf_colors.colors.red` should work.

> Current solution works and I see no need to complicate it.

Imagine you want to change the exact color. You'd have to find every place where it is used if you don't use the more abstract solution I proposed.

Thanks for your efforts!

**Comment by JostP** [comment]
> `ctf_colors.colors["red"]` and `ctf_colors.colors.red` should work.
> 

Well I don' get a crash, but I can't say that it works. I tried with your both suggestions for `pick flag` message, capture flag message isn't changed.

Zaslonska slika 2020-12-10 16-02-01

**Comment by Thomas--S** [comment]
It's not working because the color in `ctf_colors` is with the prefix `0x` and Minetest expects the prefix `#` here.

Would this function help you? https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_colors/hud.lua#L1

i.e. `ctf_colors.get_color("<playername>").css`

**Comment by JostP** [comment]
> It's not working because the color in `ctf_colors` is with the prefix `0x` and Minetest expects the prefix `#` here.
> 
> Would this function help you? https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_colors/hud.lua#L1
> 
> i.e. `ctf_colors.get_color("<playername>").css`

I am not really sure what should I use instead `"<playername>"`.
I tried with:
```
ctf_colors.get_color(attacker.team).css
ctf_colors.get_color(ctf.team(attacker.team)).css
ctf_colors.get_color(ctf.team).css
ctf_colors.get_color(ctf.team(tplayer.team)).css
```
But I get a crash or white, not-colorized  message.

**Comment by Thomas--S** [comment]
Basically, you have three options here:

1. Check if you have access to the player name as string instead of the team or
2. use the color as shown earlier by directly acessing the table (instead of calling the function). You can then replace "0x" with "#" or
3. write a new function `ctf_colors.get_team_color(<team name>)` for the ctf_colors mod.

**Comment by JostP** [comment]
Done, if works perfectly now :))
This is what I get when I change colors in `ctf_colors.colors`:
Zaslonska slika 2020-12-12 11-33-14

Can be reviewed and merged now.

**Comment by LoneWolfHT** [comment]
`red` and `blue` in those messages should be colored accordingly IMO

**Comment by JostP** [comment]
> accordingly

What do you mean?

**Comment by LoneWolfHT** [comment]
`red` colored red. `blue` colored blue, etc

**Comment by JostP** [comment]
> `red` colored red. `blue` colored blue, etc

It already is, check file changes. Screenshot above with orange color for red and purple color for blue is just to show that colors change if you change color hex numbers in ctf_colors.colors (https://github.com/MT-CTF/capturetheflag/blob/master/mods/ctf/ctf_colors/init.lua).

**Review by LoneWolfHT — APPROVED** [review]

**Pull request merged**
