### PR TITLE
make bandages change horizontal look of enemies randomly

### PR DESCRIPTION
**Pull request by farooqkz**
This PR adds a new feature to medic bandages(not normal bandages):

 - They have small chance changing the enemy's horizontal look to a random value causing distraction for them.

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
I think this is a little too clunky, and it takes medic's focus off of healing

**Comment by farooqkz** [comment]
> I think this is a little too clunky, and it takes medic's focus off of healing

Well with this low probability, it isn't rational that a medic hits an enemy constantly till this happens to them. However in a fight when a medic is supporting a knight, this could have extra good effect for the fight in the favor of medic's team. And that's my goal.

**Comment by LoneWolfHT** [comment]
It'll be too confusing for players, even if you explain it somewhere.
Subtle effects like this should be added sparingly to keep things simple

**Comment by farooqkz** [comment]
So you think medic's bandage must not have any effect on enemies?

**Comment by LoneWolfHT** [comment]
> So you think medic's bandage must not have any effect on enemies?

If it does have an effect it should be one that's big enough that it could/would replace their invincibility effect

**Pull request closed without merging**
