### PR TITLE
Fix furnace crash when dug

### PR DESCRIPTION
**Pull request by LoneWolfHT**
Tested and it seems to work

### CODE REVIEW

**Comment by ClobberXD** [comment]
Why would this even happen in the first place? :thinking: 

`on_destruct` of `furnace:furnace` is called only because a furnace exists. How can a furnace exist without an inventory?

**Comment by Thomas--S** [comment]
Furnances placed by schematics don't have any meta. There are probably a few furnances in the new maps.

**Comment by ClobberXD** [comment]
Quite likely. Then the correct fix would be to alias `furnace:furnace` to `default:stone`.

**Comment by LoneWolfHT** [comment]
> Quite likely. Then the correct fix would be to alias `furnace:furnace` to `default:stone`.

That won't cause problems with the crafting/placing of furnaces? Not very familiar with how aliasing works...

**Comment by ClobberXD** [comment]
Tested. Apparently, mods can't alias names of existing items to other names since 5.0.0 - I get a truck-load of warnings. This explains why we're seeing other removed items like grass and gold ore back in-game. The existing node-defs has to be removed first, before registering their respective aliases.

```
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:grass_1 -> air
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:grass_2 -> air
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:grass_3 -> air
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:grass_4 -> air
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:sand_with_kelp -> default:sand
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:grass_5 -> air
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:bush_leaves -> air
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:bush_stem -> air
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: default:stone_with_gold -> default:stone
2019-07-04 21:05:52: WARNING[Main]: Not registering alias, item with same name is already defined: furnace:furnace -> default:stone
```

So aliasing would not work, in this case. Then I feel that the correct thing to do would be to validate all nodes _during_ map export. While this PR would fix the crash, furnaces aren't supposed to be a part of map schems in the first place.

**Comment by LoneWolfHT** [comment]
So close this or is there a chance of this being merged?

**Comment by ClobberXD** [comment]
I don't think this is the right thing to do. It feels like a hack, IMO. Sorry.

As I said in my previous comment, node validation should take place during map export itself. The existing maps with furnaces chould be fixed manually.

**Comment by Thomas--S** [comment]
I strongly suggest to submit this bugfix to https://github.com/minetest/minetest_game because the game must not crash when a furnance without meta is dug.

**Comment by LoneWolfHT** [comment]
> I strongly suggest to submit this bugfix to https://github.com/minetest/minetest_game because the game must not crash when a furnance without meta is dug.

Ok

**Comment by LoneWolfHT** [comment]
Actually, @Thomas--S this is only a bug for CTF. There was some code added which forgot to make sure the furnace node had an inventory

**Comment by Thomas--S** [comment]
Under these conditions, I strongly recommend to reopen and merge this PR.

**Comment by LoneWolfHT** [comment]
heh, I shouldn't have deleted the fork

**Comment by ClobberXD** [comment]
You deleted the fork?! Don't you like CTF? How DARE you! :rage:

**Comment by LoneWolfHT** [comment]
Whoops, 'branch'
I must have been eating at the time or something lol

**Comment by Thomas--S** [comment]
Isn't there a "Restore branch" button?

**Comment by LoneWolfHT** [comment]
Not sure. I'll look into this later...

**Pull request closed without merging**
