### PR TITLE
Update `stairs` to latest MTG version

### PR DESCRIPTION
**Pull request by ClobberXD**
The 5.0 seems to add inner and outer stairs, which would be useful for maps and the ind_nodes PR.

Maps using stairs from 0.4-stable should still work, as the 5.0 version just adds more to the existing set of stairs and slabs.

### CODE REVIEW

**Comment by AKryukov92** [comment]
Are stairs ever available in CTF? I didn't see them for a long time.

**Comment by AKryukov92** [comment]
CTF is not survival. Why do we ever need to craft stairs?

**Comment by ClobberXD** [comment]
For maps. More specifically, maps with artificial structures like buildings.

**Comment by AKryukov92** [comment]
Do you have some specific map in mind?
It is easy to add all blocks from all mods to CTF "for maps", but if we don't make maps with them, then they will be useless.

**Comment by ClobberXD** [comment]
CTF already has `stairs` mod, but just the version from MTG 0.4.x.

**Pull request merged**
