### PR TITLE
Fix players being able to place class items in furnaces

### LINKED ISSUE #617: Class items can be put into furnace
Class items can be put in furnaces (possibly any node inventory except the team chest). This allows players to change classes and continue to possess a restricted item (like medics wielding swords).

This isn't a problem for guns because there's a class-check on use, but that's not the case with swords.

Here's what I think would be a good solution to this issue:

I *assume* the class-item-restricting code is present within an `on_metadata_inventory_put` for the team-chest. The logic in this callback should be moved to a generic `register_on_metadata_inventory_put` callback, so that it applies to all node inventories.

### PR DESCRIPTION
**Pull request by rubenwardy**
Fixes #617

****

To test:

- Be a knight; try to put a sword in a furnace. You shouldn't be able to.
- Be a shooter; try to put a rifle or a sniper rifle in a furnace. You shouldn't be able to.

### CODE REVIEW

**Comment by ClobberXD** [comment]
Note: It's still possible to completely bypass these callbacks by "swapping" slots (#56 and #576). This would only prohibit the straight-forward putting and taking actions. It's still an improvement over nothing, though.

**Comment by ClobberXD** [comment]
Btw, swapping is much less of an issue with regards to furnaces, as the furnace inv is usually empty - the player will have to place a non-class-item in the slot, and then perform the swap. Relatively complex (but still possible), compared to swapping with an already-occupied slot in chests.

**Comment by ClobberXD** [comment]
Tested; PR works. One thing came to mind though - what about class items that need to be smelted? While not very meaningful, it's certainly possible for a class to have iron lumps as class items. What do we do about this?

**Comment by LoneWolfHT** [comment]
Looks like there are merge conflicts

**Comment by LoneWolfHT** [comment]
Fixed your merge conflict

**Comment by Zipitque** [comment]
Btw...Its still works...

**Pull request merged**
