### PR TITLE
Change grapple hook warning message

### PR DESCRIPTION
**Pull request by DiamondPlane**
When you throw grapple hook it says "Your class can't use that weapon! Change your class at spawn". I changed it like in #802 PR

### CODE REVIEW

**Review by MoreKat — COMMENTED** [review]
Personally I think 'spawn' is better because that's where the flag is. A base can be quite big, it's less specific.

**Comment by moreavy** [comment]
> When you throw grapple hook it says "Your class can't use that weapon! Change your class at spawn". I changed it like in #802 PR

Why only grappling hook, also edit all the class item warnings.

**Comment by Toby1710** [comment]
> > When you throw grapple hook it says "Your class can't use that weapon! Change your class at spawn". I changed it like in #802 PR
> 
> Why only grappling hook, also edit all the class item warnings.

It's edited.

**Comment by Toby1710** [comment]
> Personally I think 'spawn' is better because that's where the flag is. A base can be quite big, it's less specific.

But... 'base' looks better... Also #802 was merged

**Comment by Panquesito7** [comment]
> > When you throw grapple hook it says "Your class can't use that weapon! Change your class at spawn". I changed it like in #802 PR
> 
> Why only grappling hook, also edit all the class item warnings.

This PR is specifically for this message. If you want to change the other messages you should make separate PR's.

**Comment by Toby1710** [comment]
I think I already changed all the item warnings. Am I right?

**Comment by moreavy** [comment]
> I think I already changed all the item warnings. Am I right?

I'll try testing today.

**Review by moreavy — APPROVED** [review]
Tested, Working Fine.

**Pull request merged**
