### PR TITLE
Replace deprecated functions with newer ones

### PR DESCRIPTION
**Pull request by Panquesito7**
Title says it all.

### CODE REVIEW

**Comment by Thomas--S** [comment]
I think it might be better to propose those changes to the original shooter mod.

As far as I know, it is planned to use the original shooter mod as a git submodule.

**Comment by Panquesito7** [comment]
> As far as I know, it is planned to use the original shooter mod as a git submodule.

Yes, but it needs testing and it has been there since a long time ago.
It also needs rebasing

Anyway, I can revert those changes and only fix a deprecated function in `dropondie` mod.
Or, I can close the PR, too.

P.S.: I don't have time to do this right now. Maybe in a few hours.

**Comment by ClobberXD** [comment]
I have fixed the deprecated function calls by `dropondie` in another PR of mine, but that hasn't been merged yet (I should've split that into a separate commit). So :+1: for that.

Regarding the changes in `shooter`... well, while I had asked you to not work on that, I also probably confused you by adding the following (https://github.com/MT-CTF/capturetheflag/pull/443#issuecomment-525148410):

> If you still really want to fix them, you should make a separate PR, as those changes are completely unrelated to this PR.

To clarify, I'm not keen to review code that's going to vanish right after getting merged.

> Yes, but it needs testing and it has been there since a long time ago.

If you're really interested in contributing, you could test that PR instead. After all, it's testing that we don't have time for - you could help by testing that PR in a thorough and systematic manner, and documenting your results in the PR page.

**Comment by Panquesito7** [comment]
> Regarding the changes in `shooter`... well, while I had asked you to not work on that, I also probably confused you by adding the following ([#443 (comment)](https://github.com/MT-CTF/capturetheflag/pull/443#issuecomment-525148410)):
> 
> > If you still really want to fix them, you should make a separate PR, as those changes are completely unrelated to this PR.
> 
> To clarify, I'm not keen to review code that's going to vanish right after getting merged.

So, I guess I should revert these changes as well (and keep the changes from `dropondie` mod).

> If you're really interested in contributing, you could test that PR instead. After all, it's testing that we don't have time for - you could help by testing that PR in a thorough and systematic manner, and documenting your results in the PR page.

I can test it as well. The only problem is that I have an old PC (old processor and graphics), and CTF will probably not work properly on my PC.

I'll probably test only with `shooter` mod enabled.
P.S.: I suggest closing this issue, as you can remove the deprecated functions (of `dropondie` mod) quickly.

**Comment by ClobberXD** [comment]
https://github.com/MT-CTF/capturetheflag/commit/08cbc414092e6880cb3566a86a9fb6992805ce7d

**Pull request closed without merging**
