### PR TITLE
Make Reinforced Cobblestone harder to break for enemy team

### PR DESCRIPTION
**Pull request by a-blob**
Make it so that Reinforced Cobblestone is easier to break for the team that placed it but harder to break for other teams.

### CODE REVIEW

**Comment by LoneWolfHT** [comment]
This works? Feels a little hacky.
It might be better to make all reinforced cobble the hardened version, but have enemies dig it twice by replacing it with a second version of itself one dug by an enemy that has a cracked texture applied. Node dig predictions should be considered with that approach

**Comment by a-blob** [comment]
A bit hacky, but works very well. I'd rather stick to this approach unless there's some unforeseen problem that might cause issues. Currently it is not complete though.

**Comment by LoneWolfHT** [comment]
How does this work with internet lag? You might be able to simulate it with minetest.after()

**Comment by a-blob** [comment]
The typical internet lag doesn't seem to affect it much. Bad internet lag (1+ seconds) makes it seem like it is dug _"twice by replacing it with a second version of itself once dug by an enemy"._

**Pull request merged**
