### PR TITLE
mark hit and kill yourself as suicide

### LINKED ISSUE #756: It is possible to hit and kill yourself
I discovered it a while ago, and it leads to very strange kill messages. I mean how is that even possible? Should you get the message "You are in your team!" ?

How to reproduce:
Using a dragonfire script:
```lua
minetest.register_globalstep(function()
	local player = minetest.localplayer
	if not player then return end
	local playercao = player:get_object()
	local control = player:get_control()
	if control.dig then
		playercao:punch()
	end
end)
```
Do not ask me how I found this out.

### PR DESCRIPTION
**Pull request by Emojigit**
Close #756 
I have no Dragonfire client so this change did not test yet.

### CODE REVIEW

**Comment by realOneplustwo** [comment]
How does this solve the underlying problem?

**Comment by Emojigit** [comment]
> underlying

What is "underlying"?

**Comment by realOneplustwo** [comment]
The problem is isn't that the kill feed isn't accurate, it is that you can hit and kill yourself.

**Comment by appgurueu** [comment]
The underlying problem has been fixed by an engine change. I suggest this PR be closed as well @LoneWolfHT.

**Pull request closed without merging**
