### PR TITLE
Spectator Privacy

### PR DESCRIPTION
**Pull request by xenonca**
- Do not show spectators in join messages (leave messages are handled by the spectator mod itself)
- Do not show spectators in /team or /status
Other relevant PR: [here](https://github.com/MT-CTF/servermods/pull/23)

### CODE REVIEW

**Review by Lucyucy — APPROVED** [review]

**Comment by savilli** [comment]
Why just don't add spectators to teams? In case there is other code with ctf.team()

**Comment by xenonca** [comment]
AFAIK joining players must be allocated to a team, not sure though

**Comment by savilli** [comment]
ctf.player(name).team can be nil. It can cause some crashes tho, but we need to fix them anyways

**Comment by xenonca** [comment]
I'm not really familiar with that code, I suppose those fixes should go into a different PR

**Comment by Emojigit** [comment]
You can also add a "spectator team" which does nothing with flags and the gameplay

**Comment by xenonca** [comment]
I assume at this point it's better to wait for CTF 3.0 to be released and rework this...

**Review by Panquesito7 — APPROVED** [review]

**Comment by xenonca** [comment]
incompatible with v3

**Pull request closed without merging**
