### PR TITLE
Change vote_kick percentage

### PR DESCRIPTION
**Pull request by TSafa-23**
Change vote_kick percentage to pass the vote from 0.8 to 0.75 (for rounds where there are few players).

### CODE REVIEW

**Comment by MinetestSam** [comment]
vote_kick was recently changed so that only players above 1000 score could vote, so I don't think this plays an important role and even if there are few players then probably less than half would be eligible to vote.

**Comment by ClobberXD** [comment]
4/5 is the perfect ratio for kick votes, in my opinion - there needs to be a significant portion of players agreeing to the kick, because it's a major decision. I'm opposed to this, sorry :-1:

**Comment by Thomas--S** [comment]
I had supported this PR before voting was restricted to players with score > 1000.

In the current situation, I think we can leave the 80% threshold. If we see concrete examples where this doesn't work, we can still consider fine-tuning.

What I would appreciate is the following: The player to be kicked shouldn't be able to vote.

**Comment by ClobberXD** [comment]
> What I would appreciate is the following: The player to be kicked shouldn't be able to vote.

PRs welcome ;)

**Pull request closed without merging**
