### PR TITLE
Improve marker in-chat message

### PR DESCRIPTION
**Pull request by JostP**
Before:

Zaslonska slika 2021-01-31 12-01-24

Now:

Zaslonska slika 2021-01-31 12-54-08

Tested and works.

### CODE REVIEW

**Review by moreavy — APPROVED** [review]
Small changes but nice ones.

**Comment by JostP** [comment]
> Small changes but nice ones.

It was quite hard to see old marker messages in chat. Now they stand out a bit more I hope.

It also adds marker string to in-chat message, so you immediately see it, and if marker tells important information, you will look around to find it.

**Comment by xenonca** [comment]
I think it's not necessary and looks worse than before. You can only see your teammates markers anyway so no need to color it. And it looks more like a chat message now. Instead that message should be moved to a HUD element like points.

**Comment by moreavy** [comment]
But the color specifies the marker messages. It is at least better than the plain white color. 😛

**Comment by xenonca** [comment]
I would probably find it less annoying if this would be displayed in the HUD instead but the chat is already so bloated with other "status messages". I don't see a point in coloring, also it's not plain white but light blue. However including the marker string is probably a good idea.

**Comment by JostP** [comment]
> I would probably find it less annoying if this would be displayed in the HUD instead but the chat is already so bloated with other "status messages". I don't see a point in coloring, also it's not plain white but light blue. However including the marker string is probably a good idea.

My main reason to create PR was to add marker string to message. If you think that colorizing it is not a good idea, I can use default message for whole message. Adding red or blue was meant to make marker mo visible.

**Comment by moreavy** [comment]
> If you think that colorizing it is not a good idea, I can use default message for whole message.
Not don't. It looks good **IMO**

**Comment by xenonca** [comment]
The light blue was probably fine, and I like the marker string being included.

**Comment by JostP** [comment]
Zaslonska slika 2021-01-31 12-54-08

**Comment by xenonca** [comment]
See #642, that was what I meant

**Pull request closed without merging**
