### PR TITLE
Refactor ctf_stats [Part 1]

### PR DESCRIPTION
**Pull request by ClobberXD**
Move all chat-commands into separate file - `chat.lua`. Some code had to be tweaked and/or moved around for the chat-commands to work properly. Partially attends to #313

Tested, works. To test, use all chat-commands and open all formspecs from `ctf_stats` mod.

### CODE REVIEW

**Comment by ClobberXD** [comment]
High priority, as this blocks [Part 2]

**Comment by Thomas--S** [comment]
I'll try to review this as soon as possible.

A suggestion for a later part of this refactoring: As far as I can see, `ctf_stats` is (nearly) the only place where hardcoded team colors (i.e. red and blue) are used. It'd be good if this could be changed to use team1 and team2 colors as set in map.conf.

**Comment by ClobberXD** [comment]
> As far as I can see, `ctf_stats` is (nearly) the only place where hardcoded team colors (i.e. red and blue) are used. It'd be good if this could be changed to use team1 and team2 colors as set in map.conf.

Currently, the following parts of CTF have been hardcoded to work with teams red and blue:

- Mass-alloc code in `ctf_alloc`
- Team doors code and textures
- Tinted hotbar textures and code in `ctf_colors`
- Team-chest textures and code
- Default team name and colour settings during init in `ctf_match` (although they're overridden once the first map loads)
- Barrier digging check during buildtime in `ctf_map`
- A huge portion of `ctf_stats`, of course

Yyyeah... `ctf_stats` is far from being the only part of CTF that hardcoded colours. And nevertheless, removing hardcoded stuff is a major undertaking (as you might've gathered by seeing Gael-de-Sailly's PRs), and I'd prefer to keep it out of the already-complex-enough multi-part refactoring PRs. :)

**Comment by Thomas--S** [comment]
According to my IDE, about 50 of about 60 occurences of "blue" are in ctf_stats.

But I'm also fine with doing the refactoring using the hard-coded names. After all, it shouldn't be too much of a problem to change it in a follow-up PR.

**Comment by ClobberXD** [comment]
Thanks, it'd be great if this PR is reviewed and merged within today at the least.

**Comment by Thomas--S** [comment]
I tried out all the ctf_stats-related chat commands and they seem to work.

I did **not** review the code because I'm not familiar with the stats-related code and I did not have the time for an extensive review.

If you carefully tested this and you are sure that you did not introduce new vulnerabilities or serious bugs, I'm fine with this being merged.

**Pull request merged**
