### PR TITLE
include `playtime` mod (fix #922)

### LINKED ISSUE #922: Include `playtime` mod
Thats useful to re-evaluate your life choices....
As far as I can see, this mod isn't laggy at all.
https://content.minetest.net/packages/Lejo/playtime/
https://github.com/Lejo1/playtime/

### PR DESCRIPTION
**Pull request by AFCMS**
fix #922

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Comment by LoneWolfHT** [comment]
This mod should use player meta, not modstorage

**Comment by AFCMS** [comment]
@LoneWolfHT OK, will open a new pr

**Comment by AFCMS** [comment]
Should I colorize messages differently?

**Comment by LoneWolfHT** [comment]
Probably doesn't need any color

**Comment by AFCMS** [comment]
@LoneWolfHT  Is it a good idea to add this to the player stats?

**Comment by LoneWolfHT** [comment]
> @LoneWolfHT  Is it a good idea to add this to the player stats (`ctf_stats`)?

If you want to make this work in v3 then probably not

**Comment by AFCMS** [comment]
So I should pr v3?

**Comment by LoneWolfHT** [comment]
Yeah, that'd probably work best.

This mod probably shouldn't be added as a submodule btw. It's unlikely to change much and submodules are a pain to manage.

**Comment by AFCMS** [comment]
Ok will work on that

**Comment by AFCMS** [comment]
Which is the v3 release date?

**Comment by LoneWolfHT** [comment]
A few hours ago

**Comment by LoneWolfHT** [comment]
On second thought please PR to https://github.com/MT-CTF/servermods

**Comment by AFCMS** [comment]
> > @LoneWolfHT  Is it a good idea to add this to the player stats (`ctf_stats`)?
> 
> If you want to make this work in v3 then probably not

But wouldn't having playtime inside stats be good?

**Comment by LoneWolfHT** [comment]
> > > @LoneWolfHT  Is it a good idea to add this to the player stats (`ctf_stats`)?
> > 
> > If you want to make this work in v3 then probably not
> 
> But wouldn't having playtime inside stats be good?

ctf_stats no longer exists, rankings are now per-mode, and I don't consider this worthy of the CTF repo. But I don't mind it as a server-specific command

**Comment by AFCMS** [comment]
even if this stat is per mode?

**Comment by LoneWolfHT** [comment]
> even if this stat is per mode?

Things get a little too complex for what they are then.
Start this off as a `/playtime` command, and it can be grown from there afterwards if players request it.

**Comment by AFCMS** [comment]
fine

**Comment by AFCMS** [comment]
> On second thought please PR to https://github.com/MT-CTF/servermods

Done

**Pull request closed without merging**
