### PR TITLE
Add craftable fence

### PR DESCRIPTION
**Pull request by Lucyucy**
This change adds craftable wooden fences. Craft fences from any wood planks + sticks.

### CODE REVIEW

**Comment by LuismiInTheZone** [comment]
O well, that was quick

**Comment by farooqkz** [comment]
What are fences good for in CTF?

**Comment by Lucyucy** [comment]
> What are fences good for in CTF?

I created this PR in response to bBADs suggestion. Fences are useful to build strong bases whithout blocking the view. They are easier to craft than doors and represent a practical extension.

**Comment by farooqkz** [comment]
While fences are better than glasses for this purpose. They are still not good enough. I will open another issue for that.

**Comment by farooqkz** [comment]
@LoneWolfHT LGTM and trivial

**Pull request merged**
