### PR TITLE
Crosshair HUD tweaks

### PR DESCRIPTION
**Pull request by TSafa-23**
UNTESTED: Should work but make sure it does before merge. Made this blind
Shortens the crosshair file size, as well as makes the central crosshair red (ff0000, easier to see during night as well). Also changes the opacity of the scope to 70% for more visibility.

(screenshot taken by soulseeker)
Screenshot_1159

### CODE REVIEW

**Comment by appgurueu** [comment]
Do not use makealpha for this one, modify the texture instead.

**Comment by TSafa-23** [comment]
Any problems with makealpha? Or is it just not worth the extra weight for rendering? Not sure how MT handles alpha or texture mods so if there are any problems I'll gladly make the changes.

**Review by Panquesito7 — APPROVED** [review]

**Comment by appgurueu** [comment]
> Any problems with makealpha? Or is it just not worth the extra weight for rendering? Not sure how MT handles alpha or texture mods so if there are any problems I'll gladly make the changes.

It makes it impossible for texture pack authors to have a crosshair with a different alpha value.

**Comment by TSafa-23** [comment]
Understood, will change

**Comment by appgurueu** [comment]
Closed as v3 removed snipers altogether.

**Comment by savilli** [comment]
Reopened as we added a crosshair back.

**Review by magnetar47 — APPROVED** [review]
I'd like to see this in. 👍

**Pull request merged**
